/* SCC Step Lookup Table for STC8H
 * Generated by gen_scc_table.py
 * Format: each line is 8 values, for freq 0-4095
 */

#ifndef SCC_TABLE_H
#define SCC_TABLE_H

#include <stc8h.h>

/* Declare in xdata (large) */
extern u32 xdata scc_step_table[4096];

/* Get step value for frequency */
#define SCC_STEP(freq) (scc_step_table[(freq)])

#endif
