#!/usr/bin/env python3
"""Generate SCC step lookup table for STC8H

Formula: step = (SCC_CLOCK/2 << (FREQ_BITS+1)) / ((freq+1) * SAMPLE_RATE)
         = (1789772 << 17) / ((freq+1) * 11025)
         = 234571236864 / ((freq+1) * 11025)
         = 21280455.47 / (freq+1)
         ≈ 21280455 / (freq+1)

Output: C array for code segment
"""

SCC_CLOCK = 1789772 * 2  # 3579545 Hz
FREQ_BITS = 16
SHIFT = FREQ_BITS + 1  # 17
SAMPLE_RATE = 11025

print(f"/* SCC Step Lookup Table */")
print(f"/* Generated by gen_scc_table.py */")
print(f"/* Formula: step = ({SCC_CLOCK//2} << {SHIFT}) / ((freq+1) * {SAMPLE_RATE}) */")
print()
print(f"const u32 code scc_step_table[4096] = {{")

for freq in range(4096):
    # Exact calculation using 64-bit
    step = ((SCC_CLOCK // 2) << SHIFT) // ((freq + 1) * SAMPLE_RATE)

    if freq % 8 == 0:
        if freq > 0:
            print()
        print(f"    /* {freq:4d} */", end="")
    print(f" {step:7}UL,", end="")

    if freq % 8 == 7:
        print()

print()
print("};")
print()
print(f"/* Usage: step = scc_step_table[freq]; */")
